#pragma once
#include <windows.h>
#include <string>
#define BRANCO FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE
#define AZUL FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define VERDE FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define AMARELO FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define VERMELHO FOREGROUND_RED | FOREGROUND_INTENSITY
#define VERMELHO_ESCURO FOREGROUND_RED
#define ROXO FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE
#define CIANO FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE
#define CINZA FOREGROUND_INTENSITY

void MostrarMensagem(std::string mensagem, int cor);